export default {
  is_authenticated: true,
  flags: [
    "android_capture/3D_minimap-2.26.0",
    "android_capture/axis-1.3.0",
    "android_capture/cloud_restore-2.0.0",
    "android_capture/crp-2.29.0",
    "android_capture/crptesting-2.29.0",
    "android_capture/detect_floors-2.23.0",
    "android_capture/hide_skip-1.3.0",
    "android_capture/import_360-1.2.0",
    "android_capture/pro3_scan_density-2.22.0",
    "android_capture/realign_scan-1.2.0",
    "android_capture/spc-1.2.0",
    "android_capture/zaya_scanning-1.6.0",
    "android_capture/zuma-2.9.0",
    "cloud_ui/allow_face_blurring",
    "cloud_ui/allow_homeaway_publish",
    "cloud_ui/attachments",
    "cloud_ui/cirrus_downloads",
    "cloud_ui/enable_selfserve_cancellation",
    "cloud_ui/experimental_metrics",
    "cloud_ui/features/measurements",
    "cloud_ui/floorplan_adv_options",
    "cloud_ui/floorplan_units_both",
    "cloud_ui/gdpr_enabled",
    "cloud_ui/homeaway",
    "cloud_ui/measurements",
    "cloud_ui/react_developer",
    "cloud_ui/react_photos",
    "cloud_ui/show_my_billing",
    "cloud_ui/JMYDCase_3",
    "cloud_ui/JMYDCase_3_ga",
    "cloud_ui/JMYDCase_3_transition",
    "cloud_ui/JMYDCase_beta_switch",
    "cloud_ui/use_zuma_addon_usage_remaining",
    "cloud_ui/use_zuma_space_flex_details",
    "cloud_ui/workshop_3_ga",
    "cloud_ui/workshop_beta",
    "discover/search",
    "discover/space_geocoding",
    "discover/zaya",
    "ingest/allow_snappy_weights_download",
    "ingest/configurable_meshing_pipeline",
    "ingest/distributed_pipeline",
    "ios_capture/3D_minimap-5.34.0",
    "ios_capture/aegis_phase_1-5.18.0",
    "ios_capture/cloud_restore-5.0.0",
    "ios_capture/crp-5.39.0",
    "ios_capture/crptesting-5.39.0",
    "ios_capture/detect_floors-5.32.0",
    "ios_capture/export_jobs-4.2.0",
    "ios_capture/firmware_v2-4.13.0",
    "ios_capture/import_360-5.20.0",
    "ios_capture/import_jobs-4.2.0",
    "ios_capture/mcp_refactor-5.7.0",
    "ios_capture/minimap3-4.18.0",
    "ios_capture/motor_mount-4.7.0",
    "ios_capture/osc_refactor-5.6.0",
    "ios_capture/pro3_scan_density-5.30.0",
    "ios_capture/realign_scan-5.6.0",
    "ios_capture/spc_beta_tag-4.3.0",
    "ios_capture/spc_lidar_complete-4.6.0",
    "ios_capture/zaya_scanning-4.16.0",
    "ios_capture/zuma-5.16.0",
    "labels",
    "mattertag_links",
    "mattertag_media",
    "mp_web/demo_space_enabled",
    "mp_web/experimental_metrics",
    "mp_web/gsv_distributed_pipeline",
    "mp_web/homeaway",
    "mp_web/homeaway_distributed_pipeline",
    "mp_web/pano_dl_ul_distributed_pipeline",
    "mp_web/workshop_beta",
    "pacioli/blk_billing",
    "pacioli/gsv_billing",
    "pacioli/model_overage_billing",
    "pacioli/model_overage_notifying",
    "pacioli/payment_show_past_due",
    "policy/manual_blur",
    "policy/verisk",
    "policy/verisk_images",
    "sc_imgopt_100",
    "show360views",
    // "JMYDCase/dollhouse-peekaboo",
    "JMYDCase/features/dollhouse-nudge",
    "JMYDCase/features/mds_prefetch",
    "JMYDCase/features/measurements",
    "JMYDCase/features/measurements-nudge",
    "JMYDCase/features/measurements-saved",
    "JMYDCase/features/meshtrim",
    "JMYDCase/features/meta_link",
    "JMYDCase/features/model-rating-dialog",
    "JMYDCase/features/model-rating-dialog-prompt",
    "JMYDCase/features/newUi_8.2",
    "JMYDCase/features/roomnav-3.1.44.19",
    "JMYDCase/features/sc2pandirection",
    "JMYDCase/features/smoothertour",
    "JMYDCase/features/space-search",
    "JMYDCase/features/tagIcons",
    "JMYDCase/features/tiled_mesh-3.1.74",
    "JMYDCase/mds",
    "JMYDCase/subscriber_prompt",
    "JMYDCase_webvr",
    "space/floorplan_adv_options",
    "uhql",
    "vrworkshop",
    "workshop/blur_mesh",
    "workshop/blur_pipeline",
    "workshop/blur_suggestions",
    "workshop/blur_suggestions_import",
    // "workshop/dollhouse-peekaboo",
    "workshop/features/advanced_tour_editing",
    "workshop/features/feedback",
    "workshop/features/measurement_settings",
    "workshop/features/meshtrim",
    "workshop/features/meta_link",
    "workshop/features/model-rating-dialog",
    "workshop/features/model-rating-dialog-prompt",
    "workshop/features/panels",
    "workshop/features/roomnav-3.1.44.19",
    "workshop/features/tiled_mesh-3.1.74",
    "workshop/tools/360_management",
    "workshop/tools/labels",
    "workshop/tools/mattertags",
    "workshop/tools/measurements",
    "workshop/tools/photos_editor",
    "workshop/tools/scan_management",
    "workshop/tools/start_location",
    "workshop/tools/tour_editor",
    "workshop/workshop_3_ga",
    "workshop_webgl",
    "ws_360snapshots",
    "ws_img_multi_dl",
    "ws_zooming",
    "zooming"
  ],
  root_folder: null,
  groups: [],
  memberships: [
    {
      root_folder: "a9VhJGsEmhW",
      default_upload_folder: null,
      flags: [
        "android_capture/3D_minimap-2.26.0",
        "android_capture/axis-1.3.0",
        "android_capture/cloud_restore-2.0.0",
        "android_capture/crp-2.29.0",
        "android_capture/crptesting-2.29.0",
        "android_capture/detect_floors-2.23.0",
        "android_capture/hide_skip-1.3.0",
        "android_capture/import_360-1.2.0",
        "android_capture/pro3_scan_density-2.22.0",
        "android_capture/realign_scan-1.2.0",
        "android_capture/spc-1.2.0",
        "android_capture/zaya_scanning-1.6.0",
        "android_capture/zuma-2.9.0",
        "cloud_ui/allow_GSV_Publish",
        "cloud_ui/allow_face_blurring",
        "cloud_ui/allow_homeaway_publish",
        "cloud_ui/attachments",
        "cloud_ui/bim",
        "cloud_ui/cirrus_downloads",
        "cloud_ui/content_distribution",
        "cloud_ui/display_external_auth",
        "cloud_ui/enable_selfserve_cancellation",
        "cloud_ui/experimental_metrics",
        "cloud_ui/features/measurements",
        "cloud_ui/floorplan_adv_options",
        "cloud_ui/floorplan_units_both",
        "cloud_ui/gdpr_enabled",
        "cloud_ui/gsv_billing",
        "cloud_ui/homeaway",
        "cloud_ui/image_rating",
        "cloud_ui/inactive_spaces",
        "cloud_ui/matterport_labs",
        "cloud_ui/measurements",
        "cloud_ui/public_access_password",
        "cloud_ui/react_developer",
        "cloud_ui/react_photos",
        "cloud_ui/show_my_billing",
        "cloud_ui/JMYDCase_3",
        "cloud_ui/JMYDCase_3_ga",
        "cloud_ui/JMYDCase_3_transition",
        "cloud_ui/JMYDCase_beta_switch",
        "cloud_ui/truplan",
        "cloud_ui/use_zuma_addon_usage_remaining",
        "cloud_ui/use_zuma_space_flex_details",
        "cloud_ui/vr",
        "cloud_ui/workshop_3_ga",
        "cloud_ui/workshop_beta",
        "discover/search",
        "discover/space_geocoding",
        "discover/zaya",
        "ingest/allow_snappy_weights_download",
        "ingest/configurable_meshing_pipeline",
        "ingest/distributed_pipeline",
        "ingest/upload",
        "ios_capture/3D_minimap-5.34.0",
        "ios_capture/aegis_phase_1-5.18.0",
        "ios_capture/cloud_restore-5.0.0",
        "ios_capture/crp-5.39.0",
        "ios_capture/crptesting-5.39.0",
        "ios_capture/detect_floors-5.32.0",
        "ios_capture/export_jobs-4.2.0",
        "ios_capture/firmware_v2-4.13.0",
        "ios_capture/import_360-5.20.0",
        "ios_capture/import_jobs-4.2.0",
        "ios_capture/mcp_refactor-5.7.0",
        "ios_capture/minimap3-4.18.0",
        "ios_capture/motor_mount-4.7.0",
        "ios_capture/osc_refactor-5.6.0",
        "ios_capture/pro3_scan_density-5.30.0",
        "ios_capture/realign_scan-5.6.0",
        "ios_capture/spc_beta_tag-4.3.0",
        "ios_capture/spc_lidar_complete-4.6.0",
        "ios_capture/zaya_scanning-4.16.0",
        "ios_capture/zuma-5.16.0",
        "labels",
        "mattertag_links",
        "mattertag_media",
        "mp_web/demo_space_enabled",
        "mp_web/experimental_metrics",
        "mp_web/gsv",
        "mp_web/gsv_distributed_pipeline",
        "mp_web/homeaway",
        "mp_web/homeaway_distributed_pipeline",
        "mp_web/inactive_spaces",
        "mp_web/make_autogallery",
        "mp_web/pano_dl_ul_distributed_pipeline",
        "mp_web/public_access_password",
        "mp_web/vr",
        "mp_web/workshop_beta",
        "pacioli/blk_billing",
        "pacioli/gsv_billing",
        "pacioli/model_overage_billing",
        "pacioli/model_overage_notifying",
        "pacioli/payment_show_past_due",
        "policy/manual_blur",
        "policy/notes",
        "policy/verisk",
        "policy/verisk_images",
        "sc_imgopt_100",
        "show360views",
        // "JMYDCase/dollhouse-peekaboo",
        "JMYDCase/features/dollhouse-nudge",
        "JMYDCase/features/mds_prefetch",
        "JMYDCase/features/measurements",
        "JMYDCase/features/measurements-nudge",
        "JMYDCase/features/measurements-saved",
        "JMYDCase/features/meshtrim",
        "JMYDCase/features/meta_link",
        "JMYDCase/features/model-rating-dialog",
        "JMYDCase/features/model-rating-dialog-prompt",
        "JMYDCase/features/newUi_8.2",
        "JMYDCase/features/roomnav-3.1.44.19",
        "JMYDCase/features/sc2pandirection",
        "JMYDCase/features/smoothertour",
        "JMYDCase/features/space-search",
        "JMYDCase/features/tagIcons",
        "JMYDCase/features/tiled_mesh-3.1.74",
        "JMYDCase/mds",
        "JMYDCase/subscriber_prompt",
        "JMYDCase_webvr",
        "space/floorplan_adv_options",
        "uhql",
        "vrworkshop",
        "workshop/blur_mesh",
        "workshop/blur_pipeline",
        "workshop/blur_suggestions",
        "workshop/blur_suggestions_import",
        // "workshop/dollhouse-peekaboo",
        "workshop/features/advanced_tour_editing",
        "workshop/features/feedback",
        "workshop/features/measurement_settings",
        "workshop/features/meshtrim",
        "workshop/features/meta_link",
        "workshop/features/model-rating-dialog",
        "workshop/features/model-rating-dialog-prompt",
        "workshop/features/panels",
        "workshop/features/roomnav-3.1.44.19",
        "workshop/features/tiled_mesh-3.1.74",
        "workshop/tools/360_management",
        "workshop/tools/labels",
        "workshop/tools/mattertags",
        "workshop/tools/measurements",
        "workshop/tools/photos_editor",
        "workshop/tools/scan_management",
        "workshop/tools/start_location",
        "workshop/tools/tour_editor",
        "workshop/workshop_3_ga",
        "workshop_webgl",
        "ws_360snapshots",
        "ws_img_multi_dl",
        "ws_zooming",
        "zooming"
      ],
      features: {
        "collaborators.quota": true,
        "org.api.tokens.quota": true,
        "org.bulktransfer": false,
        "spaces.notes": true,
        "spaces.quota": true
      },
      limits: {
        "collaborators.quota": {
          limit: 2,
          current: -1
        },
        "org.api.tokens.quota": {
          limit: 1,
          current: -1
        },
        "org.bulktransfer": {
          limit: 75,
          current: -1
        },
        "spaces.quota": {
          limit: 1,
          current: 0
        }
      },
      organization_sid: "3U1U127hHCe",
      name: "æ­¦æ±‰å°ºå­ç§‘æŠ€æœ‰é™å…¬å¸@",
      is_tos_exempt: false,
      roles: ["admin", "user"],
      capabilities: ["capture"],
      date_joined: "2024-06-05T13:25:04.366527Z",
      monogram_color_hex: "#400000",
      monogram_text: "æ­¦æ±‰",
      dismissables: {}
    }
  ],
  is_impersonation: false,
  email: "gmail@gmail.com",
  first_name: "Dawi",
  last_name: "Pong",
  title: "",
  phone_number: "",
  is_staff: false,
  is_active: true,
  is_locked: false,
  user_sid: "Lr8Hi8xUYB2",
  date_joined: "2024-06-05T13:25:04.291625Z",
  historical_sids: [],
  performance_cookies_enabled: true,
  performance_cookies_changed: null,
  group_sid: "3U1U127hHCe",
  allow_marketing_email: true,
  skedulo_resource_id: null,
  formatted_phone_number: "",
  tos_acceptance_required: false,
  privacy_policy_acceptance_required: false
}
