export enum PickingPriorityType {
  boundingSkybox = -100,
  colorOverlay = 1000,
  default = 0,
  endpoints = 21,
  ghostFloor = 51,
  ghostFloorDepthPrepass = 50,
  gizmos = 23,
  grid = 5,
  labels = 22,
  lines = 20,
  meshTrims = 5,
  panoMarker = 4,
  pinSelectedHalo = 15,
  pins = 14,
  pins360 = 6,
  portals = 9,
  reticule = 5,
  roomBounds = 7,
  rotators = 10
}
