import { MathUtils } from "three"
const s = 1e3 / 60,
  r = 89 * MathUtils.DEG2RAD,
  a = 90 * MathUtils.DEG2RAD,
  o = 0.001 * MathUtils.DEG2RAD,
  l = 10 * MathUtils.DEG2RAD,
  c = 20 * MathUtils.DEG2RAD,
  d = 30 * MathUtils.DEG2RAD,
  u = 0.25,
  h = 500,
  p = 0.1,
  m = 0.16,
  f = 0.08,
  g = Math.PI / 1e3,
  v = 0.02,
  y = 150
export const Gu = y
export const N2 = c
export const O8 = f
export const SI = s
export const TD = m
export const bC = v
export const bp = l
export const dG = d
export const jX = p
export const mP = h
export const pj = a
export const qj = u
export const uQ = r
export const v0 = g
export const zf = o
