export const FeaturesCursorKey = "features/cursor"
export const CursorStyle = {
  NONE: "none",
  DEFAULT: "default",
  MOVE: "move",
  MOVE_LF: "col-resize",
  MOVE_UD: "row-resize",
  XHAIR: "crosshair",
  PLUS: "cell",
  QUESTION: "help",
  NOPE: "not-allowed",
  FINGER: "pointer",
  TEXT: "text",
  TEXT_VERT: "vertical-text",
  ZOOM_IN: "zoom-in",
  ZOOM_OUT: "zoom-in",
  GRAB: "grab",
  GRABBING: "grabbing",
  ARROW_R: "e-resize",
  ARROW_L: "w-resize",
  ARROW_U: "n-resize",
  ARROW_D: "s-resize",
  ARROW_UR: "ne-resize",
  ARROW_UL: "nw-resize",
  ARROW_DR: "se-resize",
  ARROW_DL: "sw-resize",
  ARROW_LR: "ew-resize",
  ARROW_UD: "ns-resize",
  ARROW_URDL: "nesw-resize",
  ARROW_ULDR: "nwse-resize",
  ROOMBOUNDS_DEFAULT: "rbe-default",
  ROOMBOUNDS_MOVING: "rbe-moving",
  ROOMBOUNDS_PLACE_NODE: "rbe-place-node",
  ROOMBOUNDS_FINISH_ROOM: "rbe-finish-room"
}
