export enum CubeMapPositive {
  GL_TEXTURE_CUBE_MAP_NEGATIVE_X = 1,
  GL_TEXTURE_CUBE_MAP_NEGATIVE_Y = 3,
  GL_TEXTURE_CUBE_MAP_NEGATIVE_Z = 5,
  GL_TEXTURE_CUBE_MAP_POSITIVE_X = 0,
  GL_TEXTURE_CUBE_MAP_POSITIVE_Y = 2,
  GL_TEXTURE_CUBE_MAP_POSITIVE_Z = 4
}
