// Generated by https://quicktype.io

export interface ShowcaseConfigData {
  config?: Partial<ShowcaseConfig>
  model?: Partial<ShowcaseModel>
  queries?: Partial<ShowcaseQueries>
}

export interface ShowcaseConfig {
  mds: string
  pbf: ImprovedOctree
  sdk: ShowcaseConfigSDK
  maas: number
  plugin: ShowcaseConfigPlugin
  branch_key: string
  embedly_key: string
  raycast_lod: ImprovedOctree
  sdk_version: string
  segment_key: string
  texture_lod: ImprovedOctree
  mixpanel_key: string
  roomnav_ab_1: ImprovedOctree
  webvr_version: string
  keen_write_key: string
  merge_geometry: ImprovedOctree
  authn_login_url: string
  google_maps_key: string
  improved_octree: ImprovedOctree
  keen_project_id: string
  analytics_mp_key: string
  analytics_mp_url: string
  analytics_provider: string
  discover_space_url: string
  sdk_client_version: string
  account_register_url: string
  sdk_interface_version: string
  subscriber_prompt_a_popup: ImprovedOctree
  subscriber_prompt_b_banner: ImprovedOctree
  subscriber_prompt_denylist: string[]
  subscriber_prompt_a_delay_ms: number
}

export interface ImprovedOctree {
  ab: ShowcaseConfigAb[]
}

export interface ShowcaseConfigAb {
  value: boolean
  weight: number
}

export interface ShowcaseConfigPlugin {
  baseUrl: string
  manifestUrl: string
  applicationKey: string
}

export interface ShowcaseConfigSDK {
  test: string
  client: string
  sandbox: string
  interface: string
}

export interface ShowcaseModel {
  has_public_access_password: boolean
}

export interface ShowcaseQueries {
  GetModelPrefetch: GetModelPrefetch
}

export interface GetModelPrefetch {
  errors: PrefetchError[]
  data: PrefetchData
}

export interface PrefetchData {
  model: DataModel
  roomClassifications: RoomClassification[]
}

export interface DataModel {
  id: string
  state: string
  assets: DataModelAssets
  lod: DataModelLod
  floors: FloorElement[]
  image: DataModelImage
  locations: ModelLocation[]
  name: string
  options: ModelOptions
  publication: Publication
  rooms: DataModelRoom[]
  views: DataModelView[]
  visibility: string
  discoverable: boolean
}

export interface DataModelAssets {
  meshes: DataModelMesh[]
  textures: DataModelTexture[]
  tilesets: any[]
}

export interface DataModelMesh {
  id: string
  status: string
  filename: string
  format: string
  resolution: string
  url: string
  validUntil: string
}

export interface DataModelTexture {
  id: string
  status: string
  format: string
  resolution: string
  quality: string
  urlTemplate: string
  validUntil: string
}

export interface FloorElement {
  id: string
  meshId: number
  classification?: string
  label: string
  sequence: number
  dimensions: FloorDimensions
}

export interface FloorDimensions {
  areaFloor: number
  units: string
}

export interface DataModelImage {
  id: string
  label: string
  category: string
  height: number
  width: number
  created: string
  modified: string
  status: string
  filename: string
  format: string
  url: string
  resolutions: string[]
  type: string
  origin: string
  validUntil: string
  thumbnailUrl: string
  presentationUrl: string
  snapshotLocation: SnapshotLocation
}

export interface SnapshotLocation {
  viewMode: string
  position: LocationTion
  rotation: LocationTion
  zoom: number
  floorVisibility: any[]
  anchor: SnapshotAnchor
}

export interface SnapshotAnchor {
  id: string
  pano: SnapshotAnchorPano
}

export interface SnapshotAnchorPano {
  id: string
  placement: string
}

export interface LocationTion {
  x: number
  y: number
  z: number
  w?: number
}

export interface ModelLocation {
  id: string
  index: number
  floor: RoomClass
  neighbors: string[]
  tags: string[]
  position: LocationTion
  pano: LocationPano
  room?: RoomClass
}

export interface RoomClass {
  id: string
  meshId: number
}

export interface LocationPano {
  id: string
  label: string
  placement: string
  position: LocationTion
  rotation: LocationTion
  resolutions: string[]
  skyboxes: LocationSkybox[]
}

export interface LocationSkybox {
  resolution: string
  status: string
  urlTemplate?: string
  tileResolution: string
  tileCount: number
  tileUrlTemplate: string
  validUntil: string
}

export interface DataModelLod {
  options: string[]
}

export interface ModelOptions {
  backgroundColor: string
  dollhouseEnabled: boolean
  dollhouseLabelsEnabled: boolean
  floorSelectEnabled: boolean
  floorplanEnabled: boolean
  highlightReelEnabled: boolean
  labelsEnabled: boolean
  measurements: string
  roomBoundsEnabled: boolean
  socialSharingEnabled: boolean
  spaceSearchEnabled: boolean
  tourButtonsEnabled: boolean
  tourDollhousePanSpeed: number
  tourFastTransitionsEnabled: boolean
  tourPanAngle: number
  tourPanDirection: string
  tourPanSpeed: number
  tourTransitionSpeed: number
  tourTransitionTime: number
  tourZoomDuration: number
  unitType: string
  urlBrandingEnabled: boolean
  vrEnabled: boolean
}

export interface Publication {
  published?: boolean
  lastPublished?: string
  presentedBy?: string
  summary?: string
  contact?: PublicationContact
  options?: PublicationOptions
}

export interface PublicationContact {
  name: string
  email: string
  phoneNumber?: string
  phone?: number | string
  formattedPhone?: number | string
}

export interface PublicationOptions {
  contactEmail: boolean
  contactName: boolean
  contactPhone: boolean
  modelName: boolean
  modelSummary: boolean
  presentedBy: boolean
  address: boolean
  externalUrl: boolean
}

export interface DataModelRoom {
  id: string
  meshId: number
  floor: RoomClass
  dimensions: RoomDimensions
  tags: string[]
}

export interface RoomDimensions {
  areaFloor: number
  height?: number
  width?: number
  depth?: number
}

export interface DataModelView {
  id: string
  type: string
  name: string
  enabled: boolean
  created: string
  modified: string
}

export interface RoomClassification {
  id: string
  label: string
  defaultKeywords: string[]
}

export interface PrefetchError {
  message: string
  locations: ErrorLocation[]
  path: string[]
  extensions: Extensions
}

export interface Extensions {
  code: string
  retry: string
  httpCode: string
  classification: string
}

export interface ErrorLocation {
  line: number
  column: number
}
