// Generated by https://quicktype.io

export interface UserInfo {
  is_authenticated: boolean
  flags: string[]
  root_folder: null
  groups: any[]
  memberships: UserMembership[]
  is_impersonation: boolean
  email: string
  first_name: string
  last_name: string
  title: string
  phone_number: string
  is_staff: boolean
  is_active: boolean
  is_locked: boolean
  user_sid: string
  date_joined: string
  historical_sids: any[]
  performance_cookies_enabled: boolean
  performance_cookies_changed: null
  group_sid: string
  allow_marketing_email: boolean
  skedulo_resource_id: null
  formatted_phone_number: string
  tos_acceptance_required: boolean
  privacy_policy_acceptance_required: boolean
}

export interface UserMembership {
  root_folder: string
  default_upload_folder: null
  flags: string[]
  features: UserFeatures
  limits: UserLimits
  organization_sid: string
  name: string
  is_tos_exempt: boolean
  roles: string[]
  capabilities: string[]
  date_joined: string
  monogram_color_hex: string
  monogram_text: string
  dismissables: UserDismissables
}

export interface UserDismissables {}

export interface UserFeatures {
  "collaborators.quota": boolean
  "org.api.tokens.quota": boolean
  "org.bulktransfer": boolean
  "spaces.notes": boolean
  "spaces.quota": boolean
}

export interface UserLimits {
  "collaborators.quota": UserCollaboratorsQuota
  "org.api.tokens.quota": UserCollaboratorsQuota
  "org.bulktransfer": UserCollaboratorsQuota
  "spaces.quota": UserCollaboratorsQuota
}

export interface UserCollaboratorsQuota {
  limit: number
  current: number
}
